import type { Metadata } from "next";
import * as fonts from "@/lib/fonts";
import "./globals.css";
import { MotionConfig } from "motion/react";
import ReactLenis from "lenis/react";
import AppProvider from "@/components/app-context";
import Loader from "@/components/loader";

export const metadata: Metadata = {
  title: "Hexarchive | Guestroom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scrollbar-none">
      <body
        className={`${fonts.AkiraBold.variable} ${fonts.AkiraOutline.variable} ${fonts.OTJubileeDiamond.variable} bg-white font-ot-jubilee text-black/75 antialiased`}
      >
        <MotionConfig transition={{ duration: 0.7, easings: [0.6, 0, 0.2, 1] }}>
          <ReactLenis root>
            <AppProvider>
              <Loader>{children}</Loader>
            </AppProvider>
          </ReactLenis>
        </MotionConfig>
      </body>
    </html>
  );
}
