import type { Metadata } from "next";
import * as fonts from "@/lib/fonts";
import { SanityLive } from "@/sanity/live";
import "./globals.css";

export const metadata: Metadata = {
  title: "Hexarchive | Guestroom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scrollbar-none">
      <body
        className={`${fonts.AkiraBold.variable} ${fonts.AkiraOutline.variable} ${fonts.OTJubileeDiamond.variable} bg-white font-ot-jubilee text-black/75 antialiased`}
      >
        {children}
        <SanityLive />
      </body>
    </html>
  );
}
